# Generated by Django 5.2.5 on 2025-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Phone number'),
        ),
    ]
